apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus2
    app.kubernetes.io/part-of: pet-clinic-e2e-odsuaqkfik
  name: java-quarkus2
  namespace: has-e2e-private-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus2
    spec:
      containers:
      - image: quay.io/psturc/test-images-protected:FGAb_-java-quarkus2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
