apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus2
    app.kubernetes.io/part-of: pet-clinic-e2e-odsuaqkfik
  name: java-quarkus2
  namespace: has-e2e-private-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-quarkus2
    weight: null
status: {}
